name: Generate & Deploy Javadoc

on:
  push:
    branches: [master]

permissions:
  contents: write
  pages: write

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Generate Javadoc
        run: mvn javadoc:javadoc -DoutputDirectory=./docs -DreportOutputDirectory=./docs -DdestDir=.

      - name: Create .nojekyll file
        run: |
          # Create .nojekyll file to disable Jekyll processing
          touch ./docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
